try:
    print(4 / 2)
except NameError:
    print("Name Error!")
else:
    print("No exceptions raised by the try block!")